version: '3.8'

services:
  app:
    build: .
    ports:
      - "7000:7000"
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: 541
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
